# This sets up a PostgreSQL database
# 
# You'll need to create a pgdata volume before running this
# Run "docker volume create pgdata" from the command line
# to do this.
#
# 
FROM debian:forky-slim

COPY RequirementsManager-0.1-Linux.deb /tmp
COPY RunServices.sh /bin
RUN chmod 755 /bin/RunServices.sh
RUN apt-get update
RUN apt-get -y install postgresql postgresql-client libpqxx-dev libpistache-dev nginx sudo sed
# Set up nginx
RUN mkdir -p /etc/nginx/ssl
COPY RequirementsManagerServer.key /etc/nginx/ssl
COPY server-bundle.crt /etc/nginx/ssl
COPY nginx.conf /etc/nginx/nginx.conf
RUN mkdir -p /usr/share/nginx/html/GraphEditor
COPY GraphEditor.* /usr/share/nginx/html/GraphEditor

# Make a postgres directory to mount pgdata on
RUN mkdir -p /var/lib/postgres
RUN chown postgres:postgres /var/lib/postgres
RUN chmod 755 /var/lib/postgres

# Set up sudo
RUN sed -i 's/^%sudo.*/%sudo ALL=(ALL:ALL) NOPASSWD: ALL/' /etc/sudoers
RUN usermod -aG sudo postgres

RUN dpkg -i /tmp/RequirementsManager-0.1-Linux.deb
USER postgres

ENTRYPOINT ["/bin/RunServices.sh"]

